# Generated by Django 2.2.10 on 2020-06-07 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='projects/')),
                ('link', models.CharField(max_length=70)),
                ('technologies', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pics/')),
                ('bio', models.TextField(default='Hello there!')),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
